config/routes.rb
Rails.application.routes.draw do

get "/login" => "sessions#new"
root 'sessions#new'
post "/login" => "sessions#create"
delete "/logout" => "sessions#destroy"

  get "/menu" =>"employees#menu"
  get "/ahorros" => "savings#index"
  get "/aportaciones" => "contributions#index"
  resources :employees do
    resources :contributions do
      resources :deposit_contributions
    end
    resources :savings do
      resources :deposit_savings
    end
    resources :loans do
      resources :payments
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contribution.rb
class Contribution < ApplicationRecord
  belongs_to :employee
  has_many :deposit_contributions
end

app/models/deposit_contribution.rb
class DepositContribution < ApplicationRecord
  belongs_to :contribution
end

app/models/deposit_saving.rb
class DepositSaving < ApplicationRecord
  belongs_to :saving
end

app/models/employee.rb
class Employee < ApplicationRecord
  after_create :create_cap
  after_create :create_cah
  has_one :saving
  has_one :contribution
  has_one :loan
  has_secure_password

  validates_presence_of :name

protected
  def create_cap
    cuentap = Saving.new
    cuentap.name = self.name
    cuentap.balance = 200
    cuentap.employee_id= self.id
    cuentap.save
  end

  def create_cah
    cuentah = Contribution.new
    cuentah.name = self.name
    cuentah.balance = 200
    cuentah.employee_id= self.id
    cuentah.save
  end

end

app/models/loan.rb
class Loan < ApplicationRecord
  belongs_to :employee
  has_many :payment
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :loan
end

app/models/saving.rb
class Saving < ApplicationRecord
  belongs_to :employee
  has_many :deposit_savings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user
  before_action :authenticate

  def authenticate
    unless current_user
      redirect_to login_path
    end
  end

  def current_user
    if session[:user_id]
      @current_user = Employee.find(session[:user_id])
    end
  end

  def login(user)
    session[:user_id] = user.id
    if user.tipo == "USER"
      redirect_to user

    elsif user.tipo == "ADMIN"
      redirect_to menu_path
    else
      logout
    end
  end

  def logout
    reset_session
    redirect_to login_path
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  def new
    @employee = Employee.new
  end

  def show
    @employee = Employee.find(params[:id])
  end

  def create
    @employee = Employee.new(employee_params)

   if @employee.save
     redirect_to employees_path, notice: "EMPLEADO AGREGADO CON EXITO"
   else
     flash[:errors] = "NO SE PUDO AGREGAR UN EMPLEADO"
     render :new
end
  end

  def destroy
    @employee = Employee.find(params[:id])
    @employee.destroy
    redirect_to employees_path, notice: "EMPLEADO ELIMINADO CON EXITO"
  end

  def update
  end
  def index
    @employees = Employee.all
  end

  def menu
    
  end

  protected
  def employee_params
    params.require(:employee).permit(:name,:address,:primary_email,:secondary_email,:birth_at,:start_at,:user,:password,:tipo, :password_confirmation)
  end
end

app/controllers/loans_controller.rb
class LoansController < ApplicationController
  def new
    @employee = Employee.find(params[:employee_id])
    @loan = Employee.loans.build

  end

  def create
    @employee = Employee.find(params[:employee_id])
    @loan = Employee.loans.build(loan_params)

   if loan.save
     redirect_to @loan, notice: "PRESTAMO AGREGADO CON EXITO"
   else
     flash[:errors] = "NO SE PUDO AGREGAR UN PRESTAMO"
     render :new
  end

  def edit
  end

  def destroy
    @employee = Employee.find(params[:employee_id])
    @loan = Employee.loans.find(params[:id])
    @loan.destroy
    redirect_to @employee, notice: "PRESTAMO ELIMINADO CON EXITO"
  end

  def show
    @loan = Loan.find(params[:id])
  end

  def index
    @loan = Loan.all
  end
  protected
  def loan_params
    params.require(:employee).permit(:amount,:balance,:tipo,:periods)
  end
end

app/controllers/new_controller.rb
class NewController < ApplicationController
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  def new
  end

  def create
  end

  def edit
  end

  def destroy
  end

  def show
  end

  def index
  end
end

app/controllers/savings_controller.rb
class SavingsController < ApplicationController
  def new
    @saving = Saving.new
  end

  def create
  end

  def edit
  end

  def destroy
  end

  def show
    @saving = Saving.find(params[:id])
  end

  def index
    @savings = Saving.all
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
skip_before_action :authenticate

  def new
  	if current_user
  		redirect_to employees_path
  	end
  end

  def create
  	user = params[:session][:user]
  	passw = params[:session][:password]

  	@employee = Employee.find_by_user(user)

  	if @employee && @employee.authenticate(passw)
  		login(@employee)
  	else
  		redirect_to login_path, flash: { error: "Usuario o Contraseña Incorrecta"}
  	end
  end

  def destroy
  	logout
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contributions_helper.rb
module ContributionsHelper
end

app/helpers/deposit_savings_helper.rb
module DepositSavingsHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/loans_helper.rb
module LoansHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/savings_helper.rb
module SavingsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/employees/_employee.html.erb
<tr>
  <td><%= employee.id %></td>
  <td><%= link_to employee.name, employee_path(employee.id) %></td>
  <td><%= employee.address %></td>
  <td><%= employee.primary_email %></td>
  <td><%= employee.secondary_email %></td>
  <td><%= employee.birth_at %></td>
  <td><%= employee.start_at %></td>
  <td><%= employee.user %></td>
  <td><%= employee.tipo %></td>
  <td><%= link_to "Borrar", employee,class: "btn btn-default", method: :delete, data: {confirm: "Eliminar Empleado?"} %></td>
</tr>

app/views/employees/_employee_loan.html.erb
<table border="1" class="table  table-striped" >
  <thead>
  <tr>
    <th>ID_PRESTAMO</th>
    <th>MONTO</th>
    <th>SALDO</th>
    <th>TIPO</th>
    <th>PERIODOS</th>
    <th>FECHA_DE_CREACION</th>
    <th>ACTUALIZADO</th>
  </tr>
  </thead>

  <tbody><center>
    <td><%=loan.id%></td>
    <td><%=loan.amount%></td>
    <td><%=loan.balance%></td>
    <td><%=loan.tipo%></td>
    <td><%=loan.periods%></td>
    <td><%=loan.created_at%></td>
    <td><%=loan.updated_at%></td>
  </center></tbody>
</table>

app/views/employees/_employee_saving.html.erb
<table border="1" class="table  table-striped" >
  <thead>
  <tr>
    <th>ID_CUENTA</th>
    <th>NOMBRE_CLIENTE</th>
    <th>SALDO</th>
    <th>FECHA_DE_CREACION</th>
    <th>ACTUALIZADO</th>
  </tr>
  </thead>

  <tbody><center>
    <td><%=account.id%></td>
    <td><%=account.name%></td>
    <td><%=account.balance%></td>
    <td><%=account.created_at%></td>
    <td><%=account.updated_at%></td>
  </center></tbody>
</table>

app/views/employees/_form.html.erb
<%= form_for(employee) do |f| %>
<center>
<div class="form-group form-inline" align="center" >
  <center><b><%= f.label :name, "Nombre :" %></b></center>
  <%= f.text_field :name, size: 25,  class: "form-control" %>
</div>

<div class="form-group form-inline" align="center">
  <center><%= f.label :address, "Direccion :" %></center>
  <%= f.text_field :address, size: 25, class: "form-control" %>
</div>

<div class="form-group form-inline" align="center">
  <center><%= f.label :primary_email, "Correo Primario :" %></center>
  <%= f.text_field :primary_email, size: 25, class: "form-control" %>
</div>

<div class="form-group form-inline" align="center">
  <center><%= f.label :secondary_email, "Correo Secundario :"%> </center>
  <%= f.text_field :secondary_email, size: 25, class: "form-control" %>
</div>

<div class="form-group form-inline" align="center">
  <center><%= f.label :birth_at, "Fecha de Nacimiento :" %></center>
  <%= f.date_field :birth_at, size: 25, class: "form-control" %>
</div>

<div class="form-group form-inline" align="center">
  <center><%= f.label :start_at, "Fecha de Ingreso :" %></center>
  <%= f.date_field :start_at, size: 25, class: "form-control" %>
</div>

<div class="form-group form-inline" align="center">
  <center><%= f.label :user, "Usuario :" %></center>
  <%= f.text_field :user, size: 25, class: "form-control" %>
</div>
<div class="form-group form-inline" align="center">
  <center><%= f.label :tipo, "Tipo :" %></center>
  <%= f.text_field :tipo, size: 25, class: "form-control" %>
</div>
<div class="form-group form-inline" align="center">
  <center><%= f.label :password, "Contraseña :" %></center>
  <%= f.password_field :password, size: 25, class: "form-control" %>
</div>
<div class="form-group form-inline" align="center">
  <center><%= f.label :password_confirmation, "Confirmar Contraseña :" %></center>
  <%= f.password_field :password_confirmation, size: 25, class: "form-control" %>
  </div>
  <br>
<div class="btn-group" role="group">
    <%= f.submit "SAVE" ,class: "btn btn-primary btn-lg btn-block" %>
    <%= link_to "CANCEL",employees_path, class: "btn btn-primary btn-lg btn-block" %>
</div></center>

<%end%>

app/views/employees/index.html.erb
<br><br><br>
<div class="btn-group" role="group">
<center><%= button_to "ADD_EMPLOYEE", new_employee_path, :method => :get ,class: "btn btn-default" %></center>
</div>
<div class="top-menu" >
	<ul class="nav pull-right 	top-menu">
		<li>
				<div class="btn-group" role="group">
					<%= link_to "BACK",menu_path, class: "btn btn-primary btn-lg btn-block" %>
				</div>
		</li>
	</ul>
</div>
<center><table border=1 class="table  table-striped" >
  <thead>
    <th>ID_Afiliado</th>
    <th>Nombre</th>
    <th>Direccion</th>
    <th>Correo_Primario</th>
    <th>Correo_Secundario</th>
    <th>Fecha_Nacimiento</th>
    <th>Fecha_Inicio</th>
    <th>Usuario</th>
    <th>Tipo</th>
    <th>Borrar</th>
  </thead>

  <tbody>
    <%=render @employees %>
  </tbody>

</table></center>

app/views/employees/menu.html.erb
<br><br><br><br>

<center><h1>Bienvenido Administrador<h1>

<div class="btn-group" role="group">
<%= button_to "TABLA EMPLEADOS", employees_path, :method => :get ,class: "btn btn-default" %>
</div>

<div class="btn-group" role="group">
<%= button_to "TABLA CUENTA DE AHORROS", ahorros_path, :method => :get ,class: "btn btn-default" %>
</div>

<div class="btn-group" role="group">
<%= button_to "TABLA CUENTA DE APORTACIONES", aportaciones_path, :method => :get ,class: "btn btn-default" %>
</div>
<br>
<div class="btn-group" role="group">
<%= button_to "AÑADIR EMPLEADO", new_employee_path, :method => :get ,class: "btn btn-default" %>
</div>
</center>

app/views/employees/new.html.erb
<br><br><br><div>
<center><h1>ADD NEW EMPLOYEE</h1></center>
<%= render partial: "form", locals: {employee: @employee} %>
</div>

app/views/employees/show.html.erb
<br><br><br>

<h1>EMPLEADO AFILIADO</h1>
<table border="1" class="table  table-striped">
	<thead>
		<tr>
      <th>ID_Afiliado</th>
      <th>Nombre</th>
      <th>Direccion</th>
      <th>Correo_Primario</th>
      <th>Correo_Secundario</th>
      <th>Fecha_Nacimiento</th>
      <th>Fecha_Inicio</th>
      <th>Usuario</th>
      <th>Tipo</th>
			<th>Borrar_Empleado</th>
		</tr>
	</thead>
	<tbody>
		<%= render @employee %>
	</tbody>
</table>
<h1>CUENTA AHORROS</h1>
<%= render partial: "employee_saving", locals:{account: @employee.saving} %>
<h1>CUENTA APORTACIONES</h1>
<%= render partial: "employee_saving", locals:{account: @employee.contribution} %>
<h1>PRESTAMOS</h1>
<%if @employee.loan%>
<%= render partial: "employee_loan", locals:{loan: @employee.loan} %>
	<%end%>

app/views/loans/_loan.html.erb
<tr>
  <td><%=loan.amount%><td>
  <td><%=loan.balance%><td>
  <td><%=loan.tipo%><td>
  <td><%=loan.periods%><td>
  <td><%=loan.created_at%><td>
  <td><%=loan.updated_at%><td>
  <td><%=loan.employee_id%><td>
</tr>

app/views/loans/create.html.erb
<h1>Loans#create</h1>
<p>Find me in app/views/loans/create.html.erb</p>

app/views/loans/destroy.html.erb
<h1>Loans#destroy</h1>
<p>Find me in app/views/loans/destroy.html.erb</p>

app/views/loans/index.html.erb
<br><br><br>
<div class="btn-group" role="group">
<center><%= button_to "ADD_PAYMENT", new_employee_path, :method => :get ,class: "btn btn-default" %></center>
</div>
<center><table border=1 class="table  table-striped" >
  <thead>
    <th>ID_Prestamo</th>
    <th>Monto</th>
    <th>Saldo</th>
    <th>Tipo</th>
    <th>Periodos</th>
  </thead>

  <tbody>
    <%=render @employees %>
  </tbody>

</table></center>

app/views/loans/new.html.erb
<h1>Loans#new</h1>
<p>Find me in app/views/loans/new.html.erb</p>

app/views/loans/show.html.erb
<h1>Loans#show</h1>
<p>Find me in app/views/loans/show.html.erb</p>

app/views/payments/create.html.erb
<h1>Payments#create</h1>
<p>Find me in app/views/payments/create.html.erb</p>

app/views/payments/destroy.html.erb
<h1>Payments#destroy</h1>
<p>Find me in app/views/payments/destroy.html.erb</p>

app/views/payments/edit.html.erb
<h1>Payments#edit</h1>
<p>Find me in app/views/payments/edit.html.erb</p>

app/views/payments/index.html.erb
<h1>Payments#index</h1>
<p>Find me in app/views/payments/index.html.erb</p>

app/views/payments/new.html.erb
<h1>Payments#new</h1>
<p>Find me in app/views/payments/new.html.erb</p>

app/views/payments/show.html.erb
<h1>Payments#show</h1>
<p>Find me in app/views/payments/show.html.erb</p>

app/views/savings/_saving.html.erb
<tr>
  <td><%=saving.id%></td>
  <td><%=saving.name%></td>
  <td><%=saving.balance%></td>
  <td><%=saving.created_at%></td>
  <td><%=saving.updated_at%></td>
  <td><%=saving.employee_id%></td>
</tr>

app/views/savings/create.html.erb
<h1>Savings#create</h1>
<p>Find me in app/views/savings/create.html.erb</p>

app/views/savings/destroy.html.erb
<h1>Savings#destroy</h1>
<p>Find me in app/views/savings/destroy.html.erb</p>

app/views/savings/edit.html.erb
<h1>Savings#edit</h1>
<p>Find me in app/views/savings/edit.html.erb</p>

app/views/savings/index.html.erb
<br><br><br><br>
<div class="top-menu" >
	<ul class="nav pull-right 	top-menu">
		<li>
				<div class="btn-group" role="group">
					<%= link_to "BACK",menu_path, class: "btn btn-primary btn-lg btn-block" %>
				</div>
		</li>
	</ul>
</div><br>
<center><table border="5" class="table  table-striped">
  <thead>
    <th>ID_CUENTA</th>
    <th>NOMBRE_CLIENTE</th>
    <th>SALDO</th>
    <th>FECHA_DE_CREACION</th>
    <th>ULTIMA FECHA DE MODIFICACION</th>
  </thead>
  <tbody>
    <%=render @savings %>
  </tbody>
</table></center>

app/views/savings/new.html.erb
<h1>Savings#new</h1>
<p>Find me in app/views/savings/new.html.erb</p>

app/views/savings/show.html.erb
<br><br><br><br>
<div class="top-menu" >
	<ul class="nav pull-right 	top-menu">
		<li>
				<div class="btn-group" role="group">
					<%= link_to "BACK",employees_path, class: "btn btn-primary btn-lg btn-block" %>
				</div>
		</li>
	</ul>
</div>
<center><table border="5" class="table  table-striped">
  <thead>
    <th>ID_CUENTA</th>
    <th>NOMBRE_CLIENTE</th>
    <th>SALDO</th>
    <th>FECHA_DE_CREACION</th>
    <th>ULTIMA FECHA DE MODIFICACION</th>
  </thead>
  <tbody>
    <%=render @savings %>
  </tbody>
</table></center>