config/routes.rb
Rails.application.routes.draw do

get "/login" => "sessions#new"
root 'sessions#new'
post "/login" => "sessions#create"
delete "/logout" => "sessions#destroy"

  get "/menu" =>"employees#menu"
  get "/ahorros" => "savings#index"
  get "/aportaciones" => "contributions#index"
  resources :employees do
    resources :contributions do
      resources :deposit_contributions
    end
    resources :savings do
      resources :deposit_savings
    end
    resources :loans do
      resources :payments
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contribution.rb
class Contribution < ApplicationRecord
  belongs_to :employee
  has_many :deposit_contributions
end

app/models/deposit_contribution.rb
class DepositContribution < ApplicationRecord
  belongs_to :contribution
end

app/models/deposit_saving.rb
class DepositSaving < ApplicationRecord
  belongs_to :saving
end

app/models/employee.rb
class Employee < ApplicationRecord
  after_create :create_cap
  after_create :create_cah
  has_one :saving
  has_one :contribution
  has_one :loan
  has_secure_password

  validates_presence_of :name

protected
  def create_cap
    cuentap = Saving.new
    cuentap.name = self.name
    cuentap.balance = 200
    cuentap.employee_id= self.id
    cuentap.save
  end

  def create_cah
    cuentah = Contribution.new
    cuentah.name = self.name
    cuentah.balance = 200
    cuentah.employee_id= self.id
    cuentah.save
  end

end

app/models/loan.rb
class Loan < ApplicationRecord
  belongs_to :employee
  has_many :payment
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :loan
end

app/models/saving.rb
class Saving < ApplicationRecord
  belongs_to :employee
  has_many :deposit_savings
end

app/controllers/contributions_controller.rb
class ContributionsController < ApplicationController
  def new
  end

  def create
  end

  def edit
  end

  def destroy
  end

  def show
    @contribution = Contribution.find(params[:id])
  end

  def index
    @contributions = Contribution.all
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  def new
    @employee = Employee.new
  end

  def show
    @employee = Employee.find(params[:id])
  end

  def create
    @employee = Employee.new(employee_params)

   if @employee.save
     redirect_to employees_path, notice: "EMPLEADO AGREGADO CON EXITO"
   else
     flash[:errors] = "NO SE PUDO AGREGAR UN EMPLEADO"
     render :new
end
  end

  def destroy
    @employee = Employee.find(params[:id])
    @employee.destroy
    redirect_to employees_path, notice: "EMPLEADO ELIMINADO CON EXITO"
  end

  def update
  end
  def index
    @employees = Employee.all
  end

  def menu
    
  end

  protected
  def employee_params
    params.require(:employee).permit(:name,:address,:primary_email,:secondary_email,:birth_at,:start_at,:user,:password,:tipo, :password_confirmation)
  end
end

app/controllers/loans_controller.rb
class LoansController < ApplicationController
  def new
    @employee = Employee.find(params[:employee_id])
    @loan = Employee.loans.build

  end

  def create
    @employee = Employee.find(params[:employee_id])
    @loan = Employee.loans.build(loan_params)

   if loan.save
     redirect_to @loan, notice: "PRESTAMO AGREGADO CON EXITO"
   else
     flash[:errors] = "NO SE PUDO AGREGAR UN PRESTAMO"
     render :new
  end

  def edit
  end

  def destroy
    @employee = Employee.find(params[:employee_id])
    @loan = Employee.loans.find(params[:id])
    @loan.destroy
    redirect_to @employee, notice: "PRESTAMO ELIMINADO CON EXITO"
  end

  def show
    @loan = Loan.find(params[:id])
  end

  def index
    @loan = Loan.all
  end
  protected
  def loan_params
    params.require(:employee).permit(:amount,:balance,:tipo,:periods)
  end
end

app/controllers/new_controller.rb
class NewController < ApplicationController
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  def new
  end

  def create
  end

  def edit
  end

  def destroy
  end

  def show
  end

  def index
  end
end

app/controllers/savings_controller.rb
class SavingsController < ApplicationController
  def new
    @saving = Saving.new
  end

  def create
  end

  def edit
  end

  def destroy
  end

  def show
    @saving = Saving.find(params[:id])
  end

  def index
    @savings = Saving.all
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
skip_before_action :authenticate

  def new
  	if current_user
  		redirect_to employees_path
  	end
  end

  def create
  	user = params[:session][:user]
  	passw = params[:session][:password]

  	@employee = Employee.find_by_user(user)

  	if @employee && @employee.authenticate(passw)
  		login(@employee)
  	else
  		redirect_to login_path, flash: { error: "Usuario o Contraseña Incorrecta"}
  	end
  end

  def destroy
  	logout
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contributions_helper.rb
module ContributionsHelper
end

app/helpers/deposit_savings_helper.rb
module DepositSavingsHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/loans_helper.rb
module LoansHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/savings_helper.rb
module SavingsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/contributions/_contribution.html.erb
<tr>
  <td><%=contribution.id%></td>
  <td><%=contribution.name%></td>
  <td><%=contribution.balance%></td>
  <td><%=contribution.created_at%></td>
  <td><%=contribution.updated_at%></td>
  <td><%=contribution.employee_id%></td>
</tr>

app/views/contributions/create.html.erb
<h1>Contributions#create</h1>
<p>Find me in app/views/contributions/create.html.erb</p>

app/views/contributions/destroy.html.erb
<h1>Contributions#destroy</h1>
<p>Find me in app/views/contributions/destroy.html.erb</p>

app/views/contributions/edit.html.erb
<h1>Contributions#edit</h1>
<p>Find me in app/views/contributions/edit.html.erb</p>

app/views/contributions/index.html.erb
<br><br><br><br>
<div class="top-menu" >
	<ul class="nav pull-right 	top-menu">
		<li>
				<div class="btn-group" role="group">
					<%= link_to "BACK",menu_path, class: "btn btn-primary btn-lg btn-block" %>
				</div>
		</li>
	</ul>
</div><br>
<center><table border="5" class="table  table-striped">
  <thead>
    <th>ID_CUENTA</th>
    <th>NOMBRE_CLIENTE</th>
    <th>SALDO</th>
    <th>FECHA_DE_CREACION</th>
    <th>ULTIMA FECHA DE MODIFICACION</th>
  </thead>
  <tbody>
    <%=render @contributions%>
  </tbody>
</table></center>

app/views/contributions/new.html.erb
<h1>Contributions#new</h1>
<p>Find me in app/views/contributions/new.html.erb</p>

app/views/contributions/show.html.erb
<br><br><br><br>
<div class="top-menu" >
	<ul class="nav pull-right 	top-menu">
		<li>
				<div class="btn-group" role="group">
					<%= link_to "BACK",employees_path, class: "btn btn-primary btn-lg btn-block" %>
				</div>
		</li>
	</ul>
</div>
<center><table border="5" class="table  table-striped">
  <thead>
    <th>ID_CUENTA</th>
    <th>NOMBRE_CLIENTE</th>
    <th>SALDO</th>
    <th>FECHA_DE_CREACION</th>
    <th>ULTIMA FECHA DE MODIFICACION</th>
  </thead>
  <tbody>
    <%=render @contributions %>
  </tbody>
</table></center>